name: Publish package

on:
  push:
    branches: [master]
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - if: ${{ github.event_name == "release" }}
        run: echo "PROFILE=release" >> "$GITHUB_ENV"
      - if: ${{ github.event_name != "release" }}
        run: echo "PROFILE=dev" >> "$GITHUB_ENV"

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'

      - name: 'Run Maven'
        run: mvn -B -P ${{ env.PROFILE }} package

      - name: Publish to GitHub Packages Apache Maven
        run: mvn -B -P ${{ env.PROFILE }} deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}
